version: 0.2

phases: 
  install:
    commands:
      - echo "Install Nodejs and NPM"
      - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.3/install.sh | bash
      - nvm install node
  pre_build:
    commands:
      - echo "Installing dependencies back"
      - npm install
  build:
    commands:
      - echo "Creating the build folder"
      - npm run build

artifacts:
  files:
    - 'Dockerfile'
    - 'nginx/**/*'
    - 'build/**/*'
